### ISSUE TITLE
Various problems using 'pkg' source on systemd system.

### ISSUE THREAD

**Issue by Talkless** [salt-formulas/salt-formula-letsencrypt#6]
On Debian 8, with certbot from `jessie-backports`:
```
$ apt-cache policy certbot:
  Installed: 0.9.3-1~bpo8+2
  Candidate: 0.9.3-1~bpo8+2
  Version table:
 *** 0.9.3-1~bpo8+2 0
        100 http://httpredir.debian.org/debian/ jessie-backports/main amd64 Packages
        100 /var/lib/dpkg/status

```

system has already systemd service and timer installed:
```
$ dpkg -S /lib/systemd/system/certbot.service 
certbot: /lib/systemd/system/certbot.service
```
```
$ dpkg -S /lib/systemd/system/certbot.timer 
certbot: /lib/systemd/system/certbot.timer
```
Thought `client/init.sls` still installs it's own systemd service and timer.

Also, installed service uses configuration key that is not quite supported on Debian 8 systemd version:
```
[/etc/systemd/system/certbot.timer:6] Unknown lvalue 'RandomizedDelaySec' in section 'Timer'
```

Also, even systemd timer is deployed, cron job is still installed side by side! In result, we get timer from certbot package, from salt formula systemd timer and salt formula cron job...

So in retrospect:
* Systemd service/timer should not be installed when using 'pkg' source (unless some distributions package does not have them).
* Cron job should not be deployed if systemd timer is used, whether it's from package or jinja-generated.
* If systemd timer is rendered by salt formula, it should not use `RandomizedDelaySec` on Debian 8.

**Comment by fpytloun** [comment]
Thank you for bug report. Should be fixed now :-)

**Comment by Talkless** [comment]
About:
```
+{%- if grains.oscodename == 'jessie' %}
 RandomizedDelaySec=3600
+{%- endif %}
```
Maybe you meant `!=` ? 

Anyway I wonder, maybe it would be better to check for systemd version, it would be more universal;

From [Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843607#15) it seems that systemd  >= 229 is needed, and there is `systemd.version` key available in grains.

**Comment by fpytloun** [comment]
Good idea, didn't know about systemd.version grain. Fixed now.
